[package]
name = "caditor-sketch"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
caditor-expression.workspace = true
caditor-geometry.workspace = true

ahash.workspace = true
nalgebra.workspace = true
thiserror.workspace = true
