[package]
name = "caditor"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[features]
fuzzing = ["caditor-file/fuzzing"]

[dependencies]
caditor-document.workspace = true
caditor-expression.workspace = true
caditor-file.workspace = true
caditor-geometry.workspace = true
caditor-kernel.workspace = true
caditor-render.workspace = true
caditor-sketch.workspace = true

anyhow.workspace = true
egui.workspace = true
egui-phosphor.workspace = true
egui-wgpu.workspace = true
egui-winit = { workspace = true, features = ["accesskit"] }
env_logger.workspace = true
jiff.workspace = true
log.workspace = true
parking_lot.workspace = true
png.workspace = true
pollster.workspace = true
signal-hook.workspace = true
thiserror.workspace = true
wgpu.workspace = true
winit.workspace = true
zbus.workspace = true

[dev-dependencies]
tempfile.workspace = true
