[package]
name = "caditor-zstd"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints.rust]
unsafe_code = "deny"

[lints.clippy]
disallowed_types = "deny"
expect_used = "deny"
indexing_slicing = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unreachable = "deny"
unwrap_used = "deny"

[dependencies]
libzstd-rs-sys.workspace = true
thiserror.workspace = true
