[package]
name = "caditor-document"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
caditor-expression.workspace = true
caditor-geometry.workspace = true
caditor-kernel.workspace = true
caditor-sketch.workspace = true

log.workspace = true
parking_lot.workspace = true
rayon-core.workspace = true
thiserror.workspace = true
