[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-only"
publish = false

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
disallowed_types = "deny"
expect_used = "deny"
indexing_slicing = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unreachable = "deny"
unwrap_used = "deny"

[workspace.dependencies]
caditor-document.path = "crates/caditor-document"
caditor-expression.path = "crates/caditor-expression"
caditor-file.path = "crates/caditor-file"
caditor-geometry.path = "crates/caditor-geometry"
caditor-kernel.path = "crates/caditor-kernel"
caditor-render.path = "crates/caditor-render"
caditor-sketch.path = "crates/caditor-sketch"
caditor-step.path = "crates/caditor-step"
caditor-zstd.path = "crates/caditor-zstd"

ahash = "0.8.12"
anyhow = "1.0.104"
blake3 = { version = "1.8.7", features = ["pure"] }
crc32fast = "1.5.2"
egui = "0.36.2"
egui-phosphor = "0.14.0"
egui-wgpu = { version = "0.36.2", default-features = false }
egui-winit = {
    version = "0.36.2",
    default-features = false,
    features = ["clipboard", "wayland", "x11"]
}
env_logger = {
    version = "0.11.11",
    default-features = false,
    features = ["auto-color", "humantime"]
}
glam = "0.33.12"
jiff = {
    version = "0.2.37",
    default-features = false,
    features = ["std", "tz-system", "tzdb-zoneinfo"]
}
libzstd-rs-sys = "0.0.1-prerelease.2"
log = "0.4.34"
miniz_oxide = "0.9.1"
naga = "30.0.1"
nalgebra = "0.35.0"
parking_lot = "0.12.5"
png = "0.18.1"
pollster = "1.0.1"
rfd = { version = "0.17.2", default-features = false }
rustix = { version = "1.1.5", default-features = false }
serde = "1.0.229"
serde_json = "1.0.151"
signal-hook = { version = "0.4.4", default-features = false, features = ["iterator"] }
spade = "2.15.1"
tempfile = "3.27.0"
thiserror = "2.0.21"
wgpu = {
    version = "30.0.1",
    default-features = false,
    features = ["std", "parking_lot", "vulkan", "gles", "wgsl"]
}
winit = "0.30.13"
xattr = "1.6.1"
xxhash-rust = { version = "0.8.19", features = ["xxh3"] }

[profile.dev.package.nalgebra]
opt-level = 3

[profile.dev.package.spade]
opt-level = 3

[profile.dev.package.robust]
opt-level = 3

[profile.release]
opt-level = 3
codegen-units = 1
lto = "thin"
strip = "debuginfo"
panic = "unwind"
