[package]
name = "caditor-windows"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints.rust]
unsafe_code = "deny"

[lints.clippy]
disallowed_types = "deny"
expect_used = "deny"
indexing_slicing = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unreachable = "deny"
unwrap_used = "deny"

[target.'cfg(windows)'.dependencies]
parking_lot.workspace = true
raw-window-handle.workspace = true
windows-sys = {
    workspace = true,
    features = [
        "Win32_Foundation",
        "Win32_Graphics_Gdi",
        "Win32_Storage_FileSystem",
        "Win32_System_Console",
        "Win32_System_IO",
        "Win32_System_Ioctl",
        "Win32_System_Registry",
        "Win32_System_Threading",
        "Win32_UI_Input_KeyboardAndMouse",
        "Win32_UI_Shell",
        "Win32_UI_WindowsAndMessaging"
    ]
}

[target.'cfg(windows)'.dev-dependencies]
tempfile.workspace = true
